# Generated by Django 4.1.2 on 2023-10-17 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordExtensionValues",
            fields=[
                (
                    "extension_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="拡張ID"),
                ),
                ("extension_value", models.CharField(blank=True, max_length=256, null=True, verbose_name="拡張値")),
                ("publish_flag", models.BooleanField(verbose_name="公開フラグ")),
            ],
            options={
                "db_table": "t_discord_extension_values",
            },
        ),
        migrations.CreateModel(
            name="DiscordMemberMaster",
            fields=[
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.UUID("852206d1-a248-4289-92f9-2692387a03f6"),
                        primary_key=True,
                        serialize=False,
                        verbose_name="メンバーID",
                    ),
                ),
                ("server_id", models.BigIntegerField(unique=True, verbose_name="サーバーID")),
                ("user_id", models.BigIntegerField(unique=True, verbose_name="ユーザID")),
                ("user_name", models.CharField(max_length=120, verbose_name="ユーザ名")),
            ],
            options={
                "db_table": "m_discord_member",
            },
        ),
        migrations.CreateModel(
            name="DiscordAuthenticationToken",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="extension.discordmembermaster",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.UUID("8df42317-bf46-46e4-ab1d-302f58fa3e24"), verbose_name="トークン"),
                ),
                (
                    "generate_date_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="トークン生成日時"),
                ),
            ],
            options={
                "db_table": "t_discord_authentication_token",
            },
        ),
    ]
