# Generated by Django 4.1.2 on 2023-09-01 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordExtensionValues",
            fields=[
                (
                    "extension_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="拡張ID"),
                ),
                ("extension_value", models.CharField(blank=True, max_length=256, null=True, verbose_name="拡張値")),
                ("publish_flag", models.BooleanField(verbose_name="公開フラグ")),
            ],
            options={
                "db_table": "t_discord_extension_values",
            },
        ),
        migrations.CreateModel(
            name="DiscordMemberMaster",
            fields=[
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.UUID("dd17c506-fa63-41c0-9a5c-7e23f5666581"),
                        primary_key=True,
                        serialize=False,
                        verbose_name="メンバーID",
                    ),
                ),
                ("server_id", models.BigIntegerField(unique=True, verbose_name="サーバーID")),
                ("user_id", models.BigIntegerField(unique=True, verbose_name="ユーザID")),
                ("user_name", models.CharField(max_length=120, verbose_name="ユーザ名")),
            ],
            options={
                "db_table": "m_discord_member",
            },
        ),
        migrations.CreateModel(
            name="DiscordAuthenticationToken",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="extension.discordmembermaster",
                        to_field="user_id",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.UUID("81a5ea9e-cbea-4afc-953b-ec79a37e66f4"), verbose_name="トークン"),
                ),
                (
                    "generate_date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 1, 16, 48, 11, 898754), verbose_name="トークン生成日時"
                    ),
                ),
            ],
            options={
                "db_table": "t_discord_authentication_token",
            },
        ),
    ]
