# Generated by Django 4.1.2 on 2023-10-16 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordauthenticationtoken",
            name="generate_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 16, 19, 4, 9, 381542), verbose_name="トークン生成日時"
            ),
        ),
        migrations.AlterField(
            model_name="discordauthenticationtoken",
            name="token",
            field=models.UUIDField(default=uuid.UUID("de351653-9bf9-4f59-9626-d3b7897666a8"), verbose_name="トークン"),
        ),
        migrations.AlterField(
            model_name="discordauthenticationtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="extension.discordmembermaster",
                to_field="user_id",
            ),
        ),
        migrations.AlterField(
            model_name="discordmembermaster",
            name="member_id",
            field=models.UUIDField(
                default=uuid.UUID("f1119042-db7a-4fe3-9942-fa2fe31accbc"),
                primary_key=True,
                serialize=False,
                verbose_name="メンバーID",
            ),
        ),
    ]
