# Generated by Django 4.1.2 on 2023-10-17 02:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0002_alter_discordauthenticationtoken_generate_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordauthenticationtoken",
            name="generate_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="トークン生成日時"),
        ),
        migrations.AlterField(
            model_name="discordauthenticationtoken",
            name="token",
            field=models.UUIDField(default=uuid.UUID("3531e831-78cb-4827-9f8f-aa9632ed784e"), verbose_name="トークン"),
        ),
        migrations.AlterField(
            model_name="discordmembermaster",
            name="member_id",
            field=models.UUIDField(
                default=uuid.UUID("d7eed84d-f25f-4984-9f75-1bc51a919669"),
                primary_key=True,
                serialize=False,
                verbose_name="メンバーID",
            ),
        ),
    ]
